kind = "DojoContract"
class_hash = "0x531753bd728a66b43f1e4fd9b0dcb40590b4c8babd0fb628be29557c7be6a5"
original_class_hash = "0x531753bd728a66b43f1e4fd9b0dcb40590b4c8babd0fb628be29557c7be6a5"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/shard_dungeon_systems_metagame_metagame.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shard_dungeon::systems::metagame::metagame"
