kind = "DojoContract"
class_hash = "0x18665747cdecdef4e2501ff1e08b6c200dc5d6543692ec70249f6500f4b26c"
original_class_hash = "0x18665747cdecdef4e2501ff1e08b6c200dc5d6543692ec70249f6500f4b26c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/shard_dungeon_systems_hazard_hall_hazard_hall.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shard_dungeon::systems::hazard_hall::hazard_hall"
