[package]
cairo-version = "2.6.3"
name = "shard_dungeon"
version = "0.1.0"
# Dojo needs to be updated to support this edition. Currently
# some `pub` are in the files, but not used until this edition is supported.
# edition = "2023_11"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.2" }

[[target.dojo]]

[tool.dojo.env]
rpc_url = "http://localhost:5050/"

account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
# World address will change if the world is modified. Must be updated accordingly.
world_address = "0x4db780e0f19002fb8171f117681d4f78d790d7e160cca2b7bcbf0f9a772112c"

[tool.dojo.world]
name = "Shard Dungeon"
description = "A project to showcase the Saya settlement combined with Katana shard execution."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"

[tool.dojo.world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"
